### PR TITLE
fix rewards values, addresses #1710

### PR DESCRIPTION
**Pull request by psq**

### CODE REVIEW

**Comment by kantai** [comment]
I switched the branch to `next`, where other breaking changes are also staged -- @jcnelson, should we merge to that?

**Comment by psq** [comment]
it does not look like `get_coinbase_reward` is called yet, so should be fine either way

**Comment by jcnelson** [comment]
@kantai sounds good to me.

@psq Not quite.  The method `get_coinbase_reward()` gets used to schedule payments to miners in `make_scheduled_block_reward()`, which in turn is called by `append_block()` when advancing the chain state.  If we changed it, it would cause the miner rewards contract in the boot code to get updated with a different matured reward value than the rest of the network (this happens in `process_matured_miner_rewards()`, which is also called in `append_block()`).

**Comment by psq** [comment]
sorry, my bad, I misread the search results, you are correct!

**Comment by jcnelson** [comment]
Merging to `next`.  It'll take effect on the next chain restart.  Thanks @psq!

**Pull request merged**
