### PR TITLE
Release: 2.0.11.3.0

### PR DESCRIPTION
**Pull request by kantai**
This PR would release `2.0.11.3.0` into `master`

- [x] The release must be timed so that it does not interfere with a prepare phase. A prepare phase is currently in process, but will be completed in ~3 hours, so this release won't merge before then.
- [x] Before creating the release, the release manager must determine the version number for this release. This is a feature release, incrementing the feature version number: 2.0.11.3.0
- [x] No outstanding PRs are blockers for this release.
- [x] The release manager should open a develop -> master PR.
- [x] The release manager must update the CHANGELOG.md file with summaries what was Added, Changed, and Fixed.
- [x] Release candidate tag has been built: `2.0.11.3.0-rc2`
- [x] Once the release candidate has been built, and docker images, etc. are available, the release manager will notify various ecosystem participants to test the release candidate on various staging infrastructure:
   - [x] Stacks Foundation staging environments.
   - [x] Hiro PBC regtest network.
   - [x] Hiro PBC testnet network.
   - [x] Hiro PBC mainnet mock miner.
- [x] The release candidate should be announced in the #stacks-core-devs channel in the Stacks Discord.
- [x] The release manager will test that the release candidate successfully syncs with the current chain from genesis.
- [x] Once the final release candidate has rolled out successfully without issue on the above staging infrastructure, the release manager tags 2 additional stacks-blockchain team members to review the develop -> master PR.

### CODE REVIEW

**Comment by jcnelson** [comment]
Spinning up from genesis...

**Comment by jcnelson** [comment]
Both the Foundation's mainnet and testnet nodes have successfully reached their respective chain tips when booting from genesis.

**Review by jcnelson — APPROVED** [review]
Been running it on mainnet and testnet for a few days and everything seems fine on my end :+1:

**Review by diwakergupta — APPROVED** [review]
Happy to oblige!

**Pull request merged**
