### PR TITLE
Clarity function definitions with multiple expressions

### LINKED ISSUE #1345: Clarity function definitions to allow multiple expressions
**Clarity function definitions should allow multiple expressions in their body** instead of requiring use of the [begin](https://docs.blockstack.org/core/smart/clarityref#begin) construct when there are more than one expression. This applies to `define-private`, `define-public` and `define-read-only`.

Here is an example from the documentation of [define-public](https://docs.blockstack.org/core/smart/clarityref#define-public):

```clojure
(define-public (hello-world (input int))
  (begin (print (+ 2 input))
         (ok input)))
```

With multiple expressions in the definition body, the `begin` construct is no longer required:

```clojure
(define-public (hello-world (input int))
  (print (+ 2 input))
  (ok input))
```

The defined function evaluates each of the body expressions, returning the value of the last expression.

### PR DESCRIPTION
**Pull request by njordhov**
Resolves #1345 by implementing support for multiple expressions in Clarity function definitions.

### CODE REVIEW

**Comment by njordhov** [comment]
Most of the changes are updates to clarity code in unit tests. The core functionality is implemented by 0d4889d1403e823286485887db2017583d9db57b primarily in [DefineFunctionsParsed](https://github.com/blockstack/stacks-blockchain/pull/1435/files#diff-2fbaae6161a529f4d5e582489dc3d51d).

**Comment by njordhov** [comment]
Reason for not passing ci: `Failed to get test coverage! Error: Failed to run tests: Error: Timed out waiting for test response`. Can we run the test again?

**Comment by kantai** [comment]
If you pull in `master`, it should pass CI.

Regarding this approach -- there's a number of ways that the Clarity VM and analysis modules rely on the AST being formed solely during the ast construction -- creating new symbolic expressions outside of that module is problematic. This rewriting would need to be performed during the sugar expander pass. In order to limit the rewriting of the DefineFunctions parser, we could either (1) use macros to handle both symbolic and presymbolic expressions, or (2) add a trait that captures both ASTs, and make DefineFunctions generic in that trait.

**Comment by njordhov** [comment]
> there's a number of ways that the Clarity VM and analysis modules rely on the AST being formed solely during the ast construction -- creating new symbolic expressions outside of that module is problematic.

It is indeed beneficial to have a common canonical abstract representation that can be relied upon by the various modules. **Perhaps it's time to refactor [DefineFunctionsParsed](https://github.com/blockstack/stacks-blockchain/pull/1435/files#diff-2fbaae6161a529f4d5e582489dc3d51d) to be part of AST,** replacing the toplevel symbolic representation. It is already used not only to evaluate definitions, but also in several analysis modules. It could also be used to simplify the definition sorter in AST, and potentially also be leveraged for other AST steps.

**Pull request closed without merging**
