### PR TITLE
Clarity: Static failures for unchecked results

### PR DESCRIPTION
**Pull request by lgalabru**
This PR is addressing https://github.com/clarity-lang/reference/issues/29.

### CODE REVIEW

**Review by kantai — APPROVED** [review]
This LGTM! Do you think we should have an `(ignore ...)` method to just silence the response type?

**Review by jcnelson — APPROVED** [review]
LGTM!

**Comment by lgalabru** [comment]
@kantai

> method to just silence the response type?

Yeah that's a great nice to have idea, however it feels like going with `ignore` in terms of semantic could be a a bit confusing?
`pursue`? `continue`? post December 15th? :)

**Comment by kantai** [comment]
> @kantai
> 
> > method to just silence the response type?
> 
> Yeah that's a great nice to have idea, however it feels like going with `ignore` in terms of semantic could be a a bit confusing?
> `pursue`? `continue`? post December 15th? :)

Yeah, `ignore` could be confusing, as would the others I think. Let's just push this off for now

**Comment by lgalabru** [comment]
> Yeah, ignore could be confusing, as would the others I think. Let's just push this off for now

Sounds good. Meanwhile, I think that `(default-to ... none)` might be a legit workaround.

**Pull request merged**
