### PR TITLE
Fully automate dev setup with Gitpod

### PR DESCRIPTION
**Pull request by friedger**
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitHub and GitLab that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.

### CODE REVIEW

**Comment by diwakergupta** [comment]
@friedger thanks. Couple of questions:

- what's the use-case you have in mind here? I'm having trouble imagining someone developing the stacks blockchain on gitpod
- where is the startup.sh script used?
- I'm wondering if this belongs in a `contrib` directory instead of cluttering the root. Also wondering if this even belongs in the primary stacks-blockchain repo -- curious to hear what others think.

**Comment by friedger** [comment]
@diwakergupta It was more accident than anything else. I am setting up gitpod for my clarity contracts repo.

**Comment by R1971** [comment]
Übertragen Sie Dateien auf meine Wallet ea035fb6-2614-4d35-afa8-b2f0c698c474
reufrujevic750@gmail.com

Danke für die schnelle Rückmeldung 
LG Reuf Rujevic

**Comment by R1971** [comment]
Übertragen Sie Dateien auf meine Wallet ea035fb6-2614-4d35-afa8-b2f0c698c474

**Pull request closed without merging**
