### PR TITLE
Remove redundant clones identified by Clippy.

### PR DESCRIPTION
**Pull request by diwakergupta**
Per https://rust-lang.github.io/rust-clippy/rust-1.49.0/index.html#redundant_clone:

	Checks for a redundant clone() (and its relatives) which clones an
	owned value that is going to be dropped without further use.

	It is not always possible for the compiler to eliminate useless
	allocations and deallocations generated by redundant clone()s.

No functional changes.

### CODE REVIEW

**Review by kantai — APPROVED** [review]

**Comment by diwakergupta** [comment]
The `sampled-genesis` fails with:

```
#13 169.9 ---- tests::neon_integrations::microblock_integration_test stdout ----
#13 169.9 thread 'main' panicked at 'assertion failed: `(left == right)`
#13 169.9   left: `[88, 53]`,
#13 169.9  right: `[88, 52]`', testnet/stacks-node/src/tests/neon_integrations.rs:68:5
#13 169.9 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

That check seems related to magic-bytes:
```rust
    assert_eq!(magic_bytes.as_bytes(), &['X' as u8, '4' as u8]);
```

The `full-genesis` test fails with:
```
#12 706.7 ---- tests::neon_integrations::bitcoind_integration_test stdout ----
#12 706.7 thread 'main' panicked at 'assertion failed: `(left == right)`
#12 706.7   left: `[88, 53]`,
#12 706.7  right: `[88, 52]`', testnet/stacks-node/src/tests/neon_integrations.rs:68:5
#12 706.7 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Which is basically the same as above. Seems unrelated to this PR, does the check need to be updated to use `X5` instead of `X4` @kantai ?

```rust
pub fn xenon() -> ConfigFile {
        let burnchain = BurnchainConfigFile {
            mode: Some("xenon".to_string()),
            rpc_port: Some(18332),
            peer_port: Some(18333),
            peer_host: Some("bitcoind.xenon.blockstack.org".to_string()),
            magic_bytes: Some("X5".into()),
```

So unless there are any objections, I plan to merge this PR. I can update the integration test as a separate PR or fold it in this one.

**Comment by jcnelson** [comment]
If it's just the magic bytes, then please fix the integration tests -- they're tiny fixes.

**Comment by diwakergupta** [comment]
> If it's just the magic bytes, then please fix the integration tests -- they're tiny fixes.

Already did in my latest commit.

**Comment by diwakergupta** [comment]
`full-genesis` passed. `sampled-genesis` failed with what looks like a real, but unrelated failure:

```
#14 197.5 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: "http://127.0.0.1:26057/v2/transactions", source: TimedOut }', testnet/stacks-node/src/tests/neon_integrations.rs:230:10
```

I need one more approval to merge this @jcnelson @lgalabru :)

**Review by jcnelson — APPROVED** [review]
I think that last failing test case was fixed in my WAL PR.

**Pull request merged**
