### PR TITLE
Set an initial block limit, with benchmarks used.

### PR DESCRIPTION
**Pull request by kantai**
This PR sets an initial/draft block limit for the testnet.

This will definitely not be the block limit as we get closer to mainnet -- in particular, this block limit is set using cost constant factors which are all = 1, which disqualifies this as a useful block limit once those constant factors have been tuned.

These limits were determined using benchmarks that hit one of each of the five limit parameters (runtime, read count, read length, write count, write length), resulting in about 10s of execution time on opt-level=2 on my puny development machine.

The integration test for checking the block limit configuration setting in the Helium node currently expects a panic -- that's because the miner cannot recover from trying to mine one transaction too many. That is issue #1376, and is being worked on in a separate PR.

### CODE REVIEW

**Comment by kantai** [comment]
> This all LGTM from a "this is ready to merge" standpoint, but is there a way to run the benchmarks in such a way as to get the scaling factor required to spend 10s doing a thing?

Yes, but it's a little tricky. The reason is that as currently implemented, you can't set a 10s timer and then interrupt the Clarity VM to get the current tracker count (this is particularly tricky because the Clarity VM is a recursive interpreter). So it'd need to be a program that was kind of iteratively exploring until it got to 10 seconds. That's not so bad, but it impacts the interface, since it would need to accept a "setup script" (probably just a contract) and a "measure script" where the measure script had some kind of template variable that could be replaced by the benchmarker to increase or decrease the runtime.

**Comment by jcnelson** [comment]
Makes sense.  I don't want to block the merge on this, but if we wanted something that could come close to this without breaking the interface, what if the global context just kept an ever-growing log of all the times the cost-tracker got invoked, which stored both the time it was invoked and the _cumulative_ costs that had been seen so far?  This would effectively be a profiling feature in Clarity, but it would still serve this purpose well enough -- i.e. you'd just look at the log at around the 10s mark to see how many resources were consumed.

**Comment by muneeb-ali** [comment]
What would be a useful block limit down the road and how would we determine it? Any written material I can take a look at RE this?

**Comment by kantai** [comment]
> What would be a useful block limit down the road and how would we determine it? Any written material I can take a look at RE this?

I think the closest written material we have is the cost-analysis SIPs (which should be merged into one SIP at some point) -- [SIP 006](https://github.com/blockstack/stacks-blockchain/blob/master/sip/sip-006-runtime-cost-assessment.md) [SIP 008](https://github.com/blockstack/stacks-blockchain/blob/master/sip/sip-008-analysis-cost-assessment.md). However, those speak mostly to how runtime overheads are counted as costs. They do not really speak to setting a block limit.

When it comes to figuring out a block limit, we want to ensure some level of fairness to would-be miners -- basically, the processing of a block should not be so burdensome that it delays other miners than the previous leader from announcing their blocks (or forcing them to announce a block that does not build off of the prior block). We can perform some back-of-the-envelope calculations to find a reasonable limit:

1. Miners need to announce their commitment _before_ the next Bitcoin block -- that means they need to have received the block, processed it, and issued a commitment before the deadline.
2. If a miner wants to be 80% confident they will get to issue a commitment before the next Bitcoin block, that means the deadline is approximately 2.5 minutes (Bitcoin blocks arrive in an exponential distribution with mean of 10 minutes, meaning that the time _t_ (in minutes) where _f_ fraction of blocks arrive after _t_ is `t = ln(f) * 10`.
3. So, if a block propagates to 90% of nodes in 1 minute (which is roughly the speed of Bitcoin, though our network may be a little faster or slower to propagate -- we don't have the ability to measure this yet), that leave about 1 minute for processing the block.

So, a reasonable limit for mainnet is probably around 1 minute to process a block -- which means we'll want to target our benchmarks and cost limits for that number.

**Pull request merged**
