### PR TITLE
docs: minor fix to README

### PR DESCRIPTION
**Pull request by pavitthrap**
## Description

Modified the contract example in the README.md so that fee amount is accurate.

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [x] API reference/documentation update
- [ ] Other

### CODE REVIEW

**Review by jcnelson — APPROVED** [review]
LGTM! While you're working on the README, can you also tick the boxes for the remaining SIPs and make the text say that the mainnet has launched in Q1 2021?  Thanks!

**Review by kantai — APPROVED** [review]

**Review by reedrosenbluth — APPROVED** [review]
LGTM!

**Comment by pavitthrap** [comment]
> LGTM! While you're working on the README, can you also tick the boxes for the remaining SIPs and make the text say that the mainnet has launched in Q1 2021? Thanks!

By this do you mean modifying the message stubs for each of the SIPs? Like changing it to "This document formerly contained SIP-00x before the Stacks 2.0 mainnet launched **in Q1 2021**."

**Comment by jcnelson** [comment]
Yeah, the SIPs now all live in https://github.com/stacksgov/sips, so linking to them there would be preferable.  Also, SIP-006 and SIP-008 are activated already, as are the Xenon and Mainnet networks (but they are not checked off in the README).

**Comment by jcnelson** [comment]
Thanks @pavitthrap, looks good!

**Pull request merged**
