### PR TITLE
allow more parameters to be configured via configuration file, better default download_interval for mining on testnet

### PR DESCRIPTION
**Pull request by psq**
display configuration at startup, configure download_interval, inv_sync_interval, public_ip_address, typo

### CODE REVIEW

**Comment by psq** [comment]
is this bitcoin-test failure something I did, or this will is to be expected?

**Comment by jcnelson** [comment]
Hey @psq, thanks for sending this over!

This looks good to me, but let's get https://github.com/blockstack/stacks-blockchain/pull/1785 merged first, since I think that will fix the failing bitcoind test.

**Comment by psq** [comment]
sure, I'll check if there are merge issue after #1785 is in

**Comment by jcnelson** [comment]
@psq We got #1785 merged into `next`.  Whenever you're ready, please merge with `next` so the CI tests pass, and then we'll merge it.  Thanks again!

**Comment by psq** [comment]
@jcnelson you are too fast, was just finishing dinner and checking if the tests had passed, but it is already merged!

**Comment by jcnelson** [comment]
Haha, just happened to notice it at the right time.  Thanks again!

**Pull request merged**
