### PR TITLE
Tuple literal shorthand notation

### PR DESCRIPTION
**Pull request by njordhov**
Implements #1335 shorthand notation for tuple literals.

### CODE REVIEW

**Comment by njordhov** [comment]
Initially implements shorthand notation for the last/only property in tuple literals.

**Comment by njordhov** [comment]
Implements shorthand expansion where a comma stand in for an implicit property value, as in:

    {name, amount}

=>

    {name: name, amount: amount}

**Comment by kantai** [comment]
Thanks for this @njordhov --

I think that should address #1337, #1338, and #1339 before implementing any more syntax features for tuples.

**Comment by njordhov** [comment]
If such tuple literal shorthand notation is adopted, it should also require tuple properties with same key as value to *always* have to be in shorthand, to avoid two logically equivalent but syntactically different representations of the same property. See #1339

**Pull request closed without merging**
