### PR TITLE
Trivial updates to the cargo manifest.

### PR DESCRIPTION
**Pull request by diwakergupta**

### CODE REVIEW

**Comment by friedger** [comment]
All the docker images need an update, docs probably as well

**Comment by diwakergupta** [comment]
> All the docker images need an update, docs probably as well

baby steps :) this PR is mostly me poking around in the repo!

**Comment by CharlieC3** [comment]
I pushed up a fix for the `rustfmt` GH Action step to `master`. This branch should be **rebased** to pull in the fix via:
```bash
git pull --rebase origin master
# fix any conflicts, then
git push -f
```

**Review by kantai — APPROVED** [review]
LGTM!

**Pull request merged**
