### PR TITLE
Fixes post #1381

### PR DESCRIPTION
**Pull request by lgalabru**
Address https://github.com/blockstack/stacks-blockchain/issues/1454 and #1455

### CODE REVIEW

**Comment by jcnelson** [comment]
Looks like here and elsewhere we're consistently seeing these two tests fail:

```
    tests::integrations::bad_contract_tx_rollback
    tests::integrations::contract_stx_transfer
```

**Comment by kantai** [comment]
> Looks like here and elsewhere we're consistently seeing these two tests fail:
>
>    tests::integrations::bad_contract_tx_rollback
>    tests::integrations::contract_stx_transfer


Yeah -- these tests are non-deterministic. Part of the tests is counting how many transactions make it into each block, which depends on the execution time, unfortunately, I think if we bump up the block processing time in the integration tests, it will resolve for now, but ultimately, I think for out integration tests, we should have a more method to drive when a block finishes mining.

**Comment by zone117x** [comment]
This fixes the disk error and unresponsive server issues, however, there now appears to be a nonce bug where submitting a tx is impossible -- see https://github.com/blockstack/stacks-blockchain/issues/1461

**Comment by lgalabru** [comment]
I don't think so

**Pull request merged**
