### PR TITLE
Feature: Tuple Literals

### PR DESCRIPTION
**Pull request by njordhov**
Implements tuple literals with curly braces as implicit syntax for tuples in Clarity (issue #1234). 

Tuple literals with curly braces can immediately replace implicit tuples that use the legacy list-of-pairs syntax. Several tests have been updated accordingly, specifically _test_implicit_syntax_tuple_ and _test_factorial_contract_.

The first step implements parsing-time expansion of tuple literals into lists of pairs, with the caveat that tuple literals can be used in place of *any* list of pairs in Clarity code:

### CODE REVIEW

**Comment by njordhov** [comment]
This implementation allows curly brace tuple literals in place of _any_ list of pairs in Clarity code. Obviously this is undesirable for production, as lists of pairs are used more generally, such as in variable bindings. Upcoming revisions introduce a new PreSymbolicExpression for tuples to distinguish these from list expressions, ensuring that tuple literals only can be used where tuples are allowed.

**Comment by diwakergupta** [comment]
@njordhov thanks for the PR (and your first to this repo) 🎉 ! We'll get some eyes on this shortly, thanks for your patience.

**Comment by diwakergupta** [comment]
Meanwhile, can you address the [test failure](https://app.circleci.com/jobs/github/blockstack/blockstack-core/4705)? Might be a regression introduced by your change.

```
failures:

---- vm::ast::parser::test::test_parse_tuple_literal stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok([PreSymbolicExpression { pre_expr: List([PreSymbolicExpression { pre_expr: List([PreSymbolicExpression { pre_expr: Atom(ClarityName("id")), id: 0, span: Span { start_line: 1, start_column: 2, end_line: 1, end_column: 3 } }, PreSymbolicExpression { pre_expr: AtomValue(Int(1337)), id: 0, span: Span { start_line: 1, start_column: 5, end_line: 1, end_column: 8 } }]), id: 0, span: Span { start_line: 0, start_column: 0, end_line: 0, end_column: 0 } }]), id: 0, span: Span { start_line: 1, start_column: 1, end_line: 1, end_column: 9 } }])`,
 right: `Ok([PreSymbolicExpression { pre_expr: Tuple([PreSymbolicExpression { pre_expr: List([PreSymbolicExpression { pre_expr: Atom(ClarityName("id")), id: 0, span: Span { start_line: 1, start_column: 2, end_line: 1, end_column: 3 } }, PreSymbolicExpression { pre_expr: AtomValue(Int(1337)), id: 0, span: Span { start_line: 1, start_column: 5, end_line: 1, end_column: 8 } }]), id: 0, span: Span { start_line: 0, start_column: 0, end_line: 0, end_column: 0 } }]), id: 0, span: Span { start_line: 1, start_column: 1, end_line: 1, end_column: 9 } }])`: Should match expected tuple literal', src/vm/ast/parser/mod.rs:541:7
stack backtrace:
```

**Comment by njordhov** [comment]
> can you address the test failure? Might be a regression introduced by your change.

@diwakergupta I introduced the failing `test_parse_tuple_literal` in cc39d4d to verify that tuple literals were correctly expanded into lists. I assumed it would run when I did `cargo test` before submission, but it appears to have been missed. The test failure is addressed by 45350e9.

**Comment by njordhov** [comment]
> Do you think that this could be implemented via the SugarExpander (or a similar AST pass) such that the tuple literal only ever exists as a PreSymbolicExpression. Basically, the expander would translate PreSymbolicExpression::Tuple into the function call `(tuple (key1 value1) (key2 value2) ...)`

@kantai This is essentially what was implemented in commit df96a70 as a first step for this PR, expanding literal tuples into lists-of-pairs like the implicit tuple syntax. I have opened a new PR #1320 that forks the commit and add a line to cons `tuple` in front of the expanded expression.

**Comment by kantai** [comment]
Closing, since this feature was implemented via #1320 instead, thanks @njordhov

**Pull request closed without merging**
