### PR TITLE
Catch silently ignored errors in Clarity

### PR DESCRIPTION
**Pull request by njordhov**
First take on resolving #1409 by making Clarity's `let` no longer silently ignore errors from all but its last body expression. Instead, the first error in the body (if any) is propagated as if each of  these expressions were enclosed in`unwrap!` forms.

### CODE REVIEW

**Comment by kantai** [comment]
Thanks for opening this @njordhov --

I think this is an interesting approach, though I think it's a change to the language semantics that should be made more consistent if we want to take that approach. Currently, multi-statement let bodies are equivalent to a `(let ((...)) (begin statement-0 statement-1 ...))`, which I think should be preserved. If we are going to make a change like this to `let`, we should make it in `begin` as well (I also think that a multi-body let should be expanded by the sugar-expander to a `begin`, and then any special case handling of mult-body `let` statements can be removed --- this would also open the door to much more easily implementing multi-body functions).

**Comment by njordhov** [comment]
> If we are going to make a change like this to let, we should make it in begin as well

Commit 67ef24 implements the equivalent for `begin` - catching errors previously silently ignored. It immediately flagged problematic Clarity test code. For example, the `vm::tests::events::test_emit_nested_print_nok` test now fails **appropriately** due to catching the error in the call to `(emit-event-nok)`:

 https://github.com/blockstack/stacks-blockchain/blob/1c83de757aa6bb6665a9b68270b0adc7605abb99/src/vm/tests/events.rs#L143-L158

The two other test failures are similar: `vm::tests::assets::test_all` and `vm::tests::contracts::test_all`.

**Comment by njordhov** [comment]
@kantai What is idiomatic Clarity to explicitly ignore such error responses?

**Comment by kantai** [comment]
> @kantai What is idiomatic Clarity to explicitly ignore such error responses?

Previously -- it was `(begin )`.

I think this may be the kind of thing that would be treated better with special forms -- e.g., `(begin!` or `(let!`, which will perform an unwrap on any result types, whereas `(begin` and `(let` would continue to function as they currently do (and probably generate warnings during analysis).

**Comment by njordhov** [comment]
Silently ignoring errors is an anti-pattern. In lieu of explicitly handling error responses with e.g. `match`, errors can be conspicuously swallowed using `is-ok`. Commit 9ef0460 updates Clarity test code to explicitly swallow errors that previously were silently ignored.

**Comment by lgalabru** [comment]
@njordhov As a developer I would love to be buzzed somehow, when something like this happens, but on the other end, raising an error might be extreme (?).
What's our take on introducing the notion on `warnings` (ie non blocking error)?

**Comment by njordhov** [comment]
> As a developer I would love to be buzzed somehow, when something like this happens, but on the other end, raising an error might be extreme (?). 
 
Clarity is supposed to be _a more safe, secure and predictable smart contract language._ Defaulting to ignoring errors contradicts this goal, and is a foot gun for naive developers to let severe vulnerabilities slip into their contracts where execution continues after failures while in an inconsistent state.

To encourage more reliable and robust contracts, the Clarity analyzer should at least warn when the code would fail to handle a possible error, encouraging explicit error handling. For developer convenience, the REPL could be more lenient in allowing evaluation of code without explicit error handling.

**Comment by jcnelson** [comment]
> @kantai: I think this may be the kind of thing that would be treated better with special forms -- e.g., (begin! or (let!, which will perform an unwrap on any result types, whereas (begin and (let would continue to function as they currently do (and probably generate warnings during analysis).

@kantai do you @njordhov's proposal below is reasonable?

> To encourage more reliable and robust contracts, the Clarity analyzer should at least warn when the code would fail to handle a possible error, encouraging explicit error handling. 

I think emitting a warning from the type-checker would be a desirable feature.  Rust does this, for example, if you don't handle a `Result<..>` type.  It's helped me avoid bugs in the past.

But to be clear, I'd only be in favor of emitting warnings at instantiation time for the contract, via the analysis tooling.  I don't think it should be a type error to not handle a result, unless it's enclosed in a special form like `(begin! ..)` or `(let! ..)`.

**Comment by kantai** [comment]
Yes -- I think the approach should be something like:

* begin, let, (and if we add support for multi-line defines) defines generate _warnings_ during the analysis pass if they ignore a result.
* if we think it'd be helpful, add special forms that perform erroring unwraps

**Comment by njordhov** [comment]
>  I don't think it should be a type error to not handle a result

@jcnelson What's your reasoning for Clarity by default ignoring errors? It contradicts the goal of Clarity being a more safe, secure and predictable smart contract language.

**Comment by njordhov** [comment]
Compare to the [Zen of Python](https://www.python.org/dev/peps/pep-0020/#id2):

> Errors should never pass silently.
> Unless explicitly silenced.

**Comment by njordhov** [comment]
Propagating errors as in this PR have undesired effects on the output type of functions, and is better avoided for Clarity. However, propagating errors in begin/let blocks will be moot with https://github.com/clarity-lang/reference/issues/29 making unchecked results a static error.  If unchecked results are still permitted, such as if the analyzer is merely warning about their presence, **unchecked errors should abort contract execution rather than propagate.**

**Comment by lgalabru** [comment]
Closing, in favor of https://github.com/blockstack/stacks-blockchain/pull/2122.
Thank you for this effort @njordhov!

**Pull request closed without merging**
