### PR TITLE
Remove docs markdown files

### PR DESCRIPTION
**Pull request by agraebe**
The files seem to be local replicates of files in the docs repo: https://github.com/blockstack/docs.blockstack.

Let's remove them to avoid confusion

### CODE REVIEW

**Comment by diwakergupta** [comment]
@agraebe hmm, curious that CLA check was triggered. Are you by any chance using a non-blockstack email in your git commits?

**Comment by agraebe** [comment]
No, this is because I don't have access to the repo. had to make changes in a private repo and PR this was

**Comment by agraebe** [comment]
@kantai I can't merge due to access issues. Could you do that? Thanks!

**Comment by lgalabru** [comment]
@agraebe any take on this comment https://github.com/blockstack/stacks-blockchain/pull/1507#pullrequestreview-402682434? anything I can do to help merging this PR?

**Comment by agraebe** [comment]
Sorry I didn't respond to this yet. We have this content in our docs as "RPC API reference": https://docs.blockstack.org/core/smart/rpc-api.html

I think we can keep the file in this project but would need to maintain the docs page as well. If we are ok with that, I can make a change to the PR and leave this file in the repo. LMK.

**Comment by kantai** [comment]
Closing this in favor of #1720

**Pull request closed without merging**
