### PR TITLE
Fix: replace loses with wins

### PR DESCRIPTION
**Pull request by friedger**
## Description

User support burns cause payouts if the supported tip wins, not loses.

This PR
* changes this in the section 5. Fair mining pools. The detailed description is correct.

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [x] API reference/documentation update
- [ ] Other

## Checklist
- [x] Tag 1 of @diwakergupta

### CODE REVIEW

**Comment by CharlieC3** [comment]
I pushed up a fix for the `rustfmt` GH Action step to `master`. This branch should be **rebased** to pull in the fix via:
```bash
git pull --rebase origin master
# fix any conflicts, then
git push -f
```

**Comment by friedger** [comment]
done

**Review by jcnelson — CHANGES_REQUESTED** [review]
The original wording is correct.  The text is describing how a miner can send user burn supports for _competing_ block-commits, so that they'll get some STX even if the block-commit they sent loses.

**Comment by friedger** [comment]
Thanks for the clarification. The original wording was not clear to me.

**Pull request closed without merging**
