### PR TITLE
#[ignore] slow or serial tests

### PR DESCRIPTION
**Pull request by kantai**
This PR #[ignore]s any slow or serial tests in `cargo test` -- maybe a first step to addressing #1401.

This makes it so that just calling `$ cargo test` in a fresh repo will run the test suite in a few minutes.

To run the ignored tests, you can just run `cargo test --ignored`

I'm not sure how our CI should handle the ignored tests. It's easy enough to add that to the current CI process (by just appending `&& cargo test --ignored`), but that eliminates any benefit for the CI time (CI will still take the approximately 2 hours it currently does).

We can add that step into this PR, which would give us:

1. A local development environment where `cargo test` works.
2. A CI that, while long running, executes the full test suite.

### CODE REVIEW

**Comment by diwakergupta** [comment]
> I'm not sure how our CI should handle the ignored tests. It's easy enough to add that to the current CI process (by just appending `&& cargo test --ignored`), but that eliminates any benefit for the CI time (CI will still take the approximately 2 hours it currently does).

One approach that has worked for me in the past is to create a dedicated job (in Jenkins parlance) that runs these long tests a few times a day. Any test failures are reported as bugs for triage. So you don't trigger long tests on each PR, but you still have a process to catch regressions.

Not sure how doable that is within CircleCI or w/ Github Actions though.

**Comment by jcnelson** [comment]
Have you tried running these now-ignored tests in parallel?

**Comment by kantai** [comment]
> One approach that has worked for me in the past is to create a dedicated job (in Jenkins parlance) that runs these long tests a few times a day. Any test failures are reported as bugs for triage. So you don't trigger long tests on each PR, but you still have a process to catch regressions.
>
> Not sure how doable that is within CircleCI or w/ Github Actions though.

We could do some approximation of that setup by running the long tests on `master` branch builds only.

> Have you tried running these now-ignored tests in parallel?

Yes -- for the most part, they fail. Some fail because they cannot bind to a socket. Others seem to fail because they run out of file descriptors.

**Comment by jcnelson** [comment]
> Yes -- for the most part, they fail. Some fail because they cannot bind to a socket. Others seem to fail because they run out of file descriptors.

I was afraid of that.  Is there a way to boost the number of file descriptors available to the process?  The inability to bind to an in-use socket can be handled by tweaking each conflicting test so they all use their own port numbers.

I'm in favor of what @diwakergupta suggests, but I'm also in favor of running as many tests as we can on each PR.

**Comment by kantai** [comment]
>I was afraid of that. Is there a way to boost the number of file descriptors available to the process? The inability to bind to an in-use socket can be handled by tweaking each conflicting test so they all use their own port numbers.
>
>I'm in favor of what @diwakergupta suggests, but I'm also in favor of running as many tests as we can on each PR.

On CircleCI, I don't think this would be a problem -- the executor we use is limited to serial processing anyways, so it would probably pass those tests. The speedup we're getting on CircleCI from this PR is just a product of not running those tests -- they take ~70 minutes to run on CircleCI. I think the only way to really speed up our CI is to speed up those tests.

On a local dev environment, I'm pretty opposed to making it so that running `cargo test` requires increasing the file descriptor limit on the developer's machine. I strongly believe that if you have rust installed, you should be able to git clone and then run cargo test successfully.

**Comment by kantai** [comment]
This PR has been updated to add a conditional CI job on branches `master` and branches matching `.*net.*`, `.*marf.*`, and this branch itself, this CI job runs all of the tests.

**Comment by kantai** [comment]
> LGTM! Going forward, what's the policy for adding #[ignore] to a test? Is there a wall-clock time we're targeting? Is this written down somewhere?

I think the policy should be:

1. If the test doesn't always succeed when you run `cargo test`, it should get #[ignore]ed.
2. Otherwise, the test should run in under a minute.

Should we add this to a CONTRIBUTING section on the readme?

**Comment by jcnelson** [comment]
> If the test doesn't always succeed when you run cargo test, it should get #[ignore]ed.

I think if you commit a test that doesn't always succeed, it means you need to find the cause and fix it ;)

> A test should run in under a minute, or it should be #[ignore]ed. cargo test will complain to you if a test runs for over 60 seconds.

This sounds reasonable to me.

> Should we add this to a CONTRIBUTING section on the readme?

Yes.  I think this PR should include this policy.

**Comment by kantai** [comment]
Note: I think that the builds are intermittently failing here because rustc is OOMing, can open an issue about this. I'm not sure what the best approach for dealing with that is...

**Pull request merged**
