### PR TITLE
Fixes on event dispatcher

### PR DESCRIPTION
**Pull request by lgalabru**
I should have clicked with this feedback: https://github.com/blockstack/stacks-blockchain/pull/1718#discussion_r450489368
Since we are creating the connection manually:
```rust
let stream = match TcpStream::connect(self.endpoint.clone())
```
We don't want to suffix the endpoint with `/` anymore, and we should produce a parsing error when such a value is provided in the settings (mimicking the behaviour of `rpc_bind`, `p2p_bind`, `prometheus_bind`).
This PR is fixing this.

While testing this PR with a local sidecar, I noticed that the `Content-type` header was being added twice:
```
POST /new_block HTTP/1.1
host: 127.0.0.1:3000
content-length: 979
date: Tue, 07 Jul 2020 03:50:10 GMT
content-type: application/json
content-length: 979
```
This PR is also addressing this issue.

### CODE REVIEW

**Comment by kantai** [comment]
One of the neon integration tests will test the event observer behavior -- that seems to be failing in this branch:

```
$ BITCOIND_TEST=1 cargo test --workspace -- --ignored microblock_integration_test
...
Event dispatcher: connection failed  - Custom { kind: InvalidInput, error: VerboseError { source: Custom { kind: InvalidInput, error: "invalid port value" }, message: "could not resolve address `\"http://localhost:50303/\"`" } }
```

Can you update that test as well?

**Comment by diwakergupta** [comment]
@kantai beat me to it, I was just typing "@lgalabru do we have any tests for the event dispatcher and if not, can we add some" :) 

Aaron, why are these tests ignored by default? Are they long-lived or flaky?

**Comment by kantai** [comment]
> Aaron, why are these tests ignored by default? Are they long-lived or flaky?

They require `bitcoind` and they can't run in parallel -- however, we should be able to get these to run as a job in CircleCI.

**Comment by lgalabru** [comment]
@kantai thank you for catching this. Test updated, and passing:
```

    Finished test [unoptimized + debuginfo] target(s) in 30.20s
     Running /Users/ludovic/Coding/blockstack/stacks-blockchain/target/debug/deps/bitcoin_neon_controller-76479ba6c9b59504

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /Users/ludovic/Coding/blockstack/stacks-blockchain/target/debug/deps/blockstack_lib-8e9df87efb959528

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1130 filtered out

     Running /Users/ludovic/Coding/blockstack/stacks-blockchain/target/debug/deps/blockstack_cli-cfb7cd95374cdc9b

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out

     Running /Users/ludovic/Coding/blockstack/stacks-blockchain/target/debug/deps/blockstack_core-11aae86205e8fe1f

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /Users/ludovic/Coding/blockstack/stacks-blockchain/target/debug/deps/clarity_cli-f3e71cb465971387

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /Users/ludovic/Coding/blockstack/stacks-blockchain/target/debug/deps/stacks_node-c5a4411691c2b0ea

running 1 test
INFO [1594131919.623] [testnet/stacks-node/src/tests/neon_integrations.rs:88] [ThreadId(3)] Spawning warp server
INFO [1594131922.055] [testnet/stacks-node/src/run_loop/neon.rs:86] [ThreadId(14)] Miner node: checking UTXOs at address: mtFzK54XtpktHj7fKonFExEPEGkUMsiXdy
INFO [1594131922.065] [testnet/stacks-node/src/run_loop/neon.rs:94] [ThreadId(14)] Miner node: starting up, UTXOs found.
INFO [1594131922.072] [src/chainstate/stacks/index/marf.rs:761] [ThreadId(14)] First-ever block 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206 in /tmp/stacks-testnet-6f1afb371a3e514e/burnchain/db/bitcoin/regtest/burn.db/marf
INFO [1594131922.197] [src/burnchains/burnchain.rs:855] [ThreadId(14)] Node will fetch burnchain blocks 0-201...
INFO [1594131928.743] [src/chainstate/stacks/index/marf.rs:761] [ThreadId(14)] First-ever block 8aeecfa0b9f2ac7818863b1362241e4f32d06b100ae9d1c0fbcc4ed61b91b17a in /tmp/stacks-testnet-6f1afb371a3e514e/chainstate/chain-00000080-testnet/vm/clarity/marf
INFO [1594131928.908] [src/chainstate/stacks/db/accounts.rs:183] [ThreadId(14)] ST2VHM28V9E5QCRD6C73215KAPSBKQGPWTEE5CMQT credited: 10000 uSTX
INFO [1594131928.912] [src/chainstate/stacks/db/accounts.rs:183] [ThreadId(14)] ST3WM51TCWMJYGZS1QFMC28DH5YP86782YGR113C1 credited: 100300 uSTX
INFO [1594131928.921] [src/chainstate/stacks/index/marf.rs:761] [ThreadId(14)] First-ever block 8aeecfa0b9f2ac7818863b1362241e4f32d06b100ae9d1c0fbcc4ed61b91b17a in /tmp/stacks-testnet-6f1afb371a3e514e/chainstate/chain-00000080-testnet/vm/index
INFO [1594131928.934] [testnet/stacks-node/src/event_dispatcher.rs:286] [ThreadId(14)] Registering event observer at: localhost:50303
BOOTSTRAP WITH []
INFO [1594131929.243] [src/net/db.rs:141] [ThreadId(14)] Peer's public key: 044773135bdc76773f6fb16906b29575b6b84ca7e15fe005f7a471b9312295b1ea6259529548874fc1598adda90ea742cd1cc3c9bccf0ac06ef0866f8eea66c9e4
INFO [1594131929.271] [testnet/stacks-node/src/neon_node.rs:620] [ThreadId(14)] Bound HTTP server on: 127.0.0.1:35906
INFO [1594131929.271] [testnet/stacks-node/src/neon_node.rs:621] [ThreadId(14)] Bound P2P server on: 127.0.0.1:20548
INFO [1594131929.273] [testnet/stacks-node/src/run_loop/neon.rs:118] [ThreadId(14)] Begin run loop
INFO [1594131929.289] [src/burnchains/bitcoin/spv.rs:682] [ThreadId(14)] Truncate received headers from block range 186-201 to range 186-1
INFO [1594131929.303] [src/burnchains/burnchain.rs:855] [ThreadId(14)] Node will fetch burnchain blocks 201-202...
WARN [1594131929.370] [testnet/stacks-node/src/neon_node.rs:657] [ThreadId(14)] Skipped tenure because no active VRF key. Trying to register one.
INFO [1594131929.438] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:328] [ThreadId(18)] Miner node: submitting leader_key_register op - 04ee0b1602eb18fef7986887a7e8769a30c9df981d33c8380d255edef003abdcd243a0eb74afdf6740e6c423e62aec631519a24cf5b1d62bf8a3e06ddc695dcb77
INFO [1594131934.425] [src/burnchains/burnchain.rs:855] [ThreadId(14)] Node will fetch burnchain blocks 202-203...
INFO [1594131934.533] [testnet/stacks-node/src/neon_node.rs:872] [ThreadId(14)] Received burnchain block #203 including key_register_op - ST25WA53N4PWF8XZGQH2J5A4CGCWV4JADPM8MHTRV
INFO [1594131934.533] [testnet/stacks-node/src/neon_node.rs:651] [ThreadId(14)] Sleeping 0 before issuing tenure
WARN [1594131934.543] [testnet/stacks-node/src/neon_node.rs:789] [ThreadId(18)] No Stacks chain tip known, attempting to mine a genesis block
INFO [1594131934.587] [src/chainstate/stacks/miner.rs:431] [ThreadId(18)] Miner: mined anchored block 401ae1ec3ebc2fdb989c261e1a141bcd4209840150736f5797583e6221bbd540, parent block 0000000000000000000000000000000000000000000000000000000000000000
INFO [1594131934.592] [testnet/stacks-node/src/neon_node.rs:807] [ThreadId(18)] Genesis block assembled: 401ae1ec3ebc2fdb989c261e1a141bcd4209840150736f5797583e6221bbd540, with 1 txs
INFO [1594131934.638] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:378] [ThreadId(18)] Miner node: submitting leader_block_commit op - 04ee0b1602eb18fef7986887a7e8769a30c9df981d33c8380d255edef003abdcd243a0eb74afdf6740e6c423e62aec631519a24cf5b1d62bf8a3e06ddc695dcb77
INFO [1594131934.686] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:328] [ThreadId(18)] Miner node: submitting leader_key_register op - 04ee0b1602eb18fef7986887a7e8769a30c9df981d33c8380d255edef003abdcd243a0eb74afdf6740e6c423e62aec631519a24cf5b1d62bf8a3e06ddc695dcb77
INFO [1594131939.602] [src/burnchains/burnchain.rs:855] [ThreadId(14)] Node will fetch burnchain blocks 203-204...
INFO [1594131939.720] [testnet/stacks-node/src/neon_node.rs:852] [ThreadId(14)] Received burnchain block #204 including block_commit_op (winning) - mtFzK54XtpktHj7fKonFExEPEGkUMsiXdy
INFO [1594131939.722] [testnet/stacks-node/src/neon_node.rs:872] [ThreadId(14)] Received burnchain block #204 including key_register_op - ST25WA53N4PWF8XZGQH2J5A4CGCWV4JADPM8MHTRV
INFO [1594131939.722] [testnet/stacks-node/src/neon_node.rs:651] [ThreadId(14)] Sleeping 0 before issuing tenure
INFO [1594131939.722] [testnet/stacks-node/src/neon_node.rs:412] [ThreadId(18)] Won sortition! stacks_header=401ae1ec3ebc2fdb989c261e1a141bcd4209840150736f5797583e6221bbd540, burn_header=5393236506fbd803b73b544eac8395ab0ab6e9a9020c6a04997b8fdb2b4bce7b
WARN [1594131939.874] [testnet/stacks-node/src/neon_node.rs:445] [ThreadId(18)] Failed to mine microblock: No transactions to mine
INFO [1594131939.916] [src/chainstate/stacks/miner.rs:431] [ThreadId(18)] Miner: mined anchored block 423ccac2fec452c927d9ebd9d3497e63813728e4695d933c5b9d5b581c6e2e40, parent block 401ae1ec3ebc2fdb989c261e1a141bcd4209840150736f5797583e6221bbd540
INFO [1594131939.920] [testnet/stacks-node/src/neon_node.rs:807] [ThreadId(18)] Stacks block assembled: 423ccac2fec452c927d9ebd9d3497e63813728e4695d933c5b9d5b581c6e2e40, with 1 txs
INFO [1594131939.964] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:378] [ThreadId(18)] Miner node: submitting leader_block_commit op - 04ee0b1602eb18fef7986887a7e8769a30c9df981d33c8380d255edef003abdcd243a0eb74afdf6740e6c423e62aec631519a24cf5b1d62bf8a3e06ddc695dcb77
INFO [1594131940.004] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:328] [ThreadId(18)] Miner node: submitting leader_key_register op - 04ee0b1602eb18fef7986887a7e8769a30c9df981d33c8380d255edef003abdcd243a0eb74afdf6740e6c423e62aec631519a24cf5b1d62bf8a3e06ddc695dcb77
INFO [1594131944.808] [src/burnchains/burnchain.rs:855] [ThreadId(14)] Node will fetch burnchain blocks 204-205...
INFO [1594131944.957] [testnet/stacks-node/src/neon_node.rs:852] [ThreadId(14)] Received burnchain block #205 including block_commit_op (winning) - mtFzK54XtpktHj7fKonFExEPEGkUMsiXdy
INFO [1594131944.959] [testnet/stacks-node/src/neon_node.rs:872] [ThreadId(14)] Received burnchain block #205 including key_register_op - ST25WA53N4PWF8XZGQH2J5A4CGCWV4JADPM8MHTRV
INFO [1594131944.959] [testnet/stacks-node/src/neon_node.rs:651] [ThreadId(14)] Sleeping 0 before issuing tenure
INFO [1594131944.959] [testnet/stacks-node/src/neon_node.rs:412] [ThreadId(18)] Won sortition! stacks_header=423ccac2fec452c927d9ebd9d3497e63813728e4695d933c5b9d5b581c6e2e40, burn_header=0ec5741b1260bd00702fef1d8ea3d8c8c3a70e09f6f6d0cd46091c5a5e380e6c
INFO [1594131945.093] [testnet/stacks-node/src/neon_node.rs:708] [ThreadId(18)] Minted microblock with 1 transactions
WARN [1594131945.157] [src/chainstate/stacks/miner.rs:652] [ThreadId(18)] Failed to apply tx 738e4d44636023efa08374033428e44eca490582bd39a6e61f3b6cf749b4214c: InvalidStacksTransaction("Invalid transaction anchor mode for anchored data")
INFO [1594131945.157] [src/chainstate/stacks/miner.rs:431] [ThreadId(18)] Miner: mined anchored block 4408acfcc516ae8ae86306811e82a45f3bf57a4a11ae0083a367af24d47ef645, parent block 423ccac2fec452c927d9ebd9d3497e63813728e4695d933c5b9d5b581c6e2e40
INFO [1594131945.162] [testnet/stacks-node/src/neon_node.rs:807] [ThreadId(18)] Stacks block assembled: 4408acfcc516ae8ae86306811e82a45f3bf57a4a11ae0083a367af24d47ef645, with 1 txs
INFO [1594131945.202] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:378] [ThreadId(18)] Miner node: submitting leader_block_commit op - 04ee0b1602eb18fef7986887a7e8769a30c9df981d33c8380d255edef003abdcd243a0eb74afdf6740e6c423e62aec631519a24cf5b1d62bf8a3e06ddc695dcb77
INFO [1594131945.248] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:328] [ThreadId(18)] Miner node: submitting leader_key_register op - 04ee0b1602eb18fef7986887a7e8769a30c9df981d33c8380d255edef003abdcd243a0eb74afdf6740e6c423e62aec631519a24cf5b1d62bf8a3e06ddc695dcb77
INFO [1594131950.034] [src/burnchains/burnchain.rs:855] [ThreadId(14)] Node will fetch burnchain blocks 205-206...
INFO [1594131950.186] [testnet/stacks-node/src/neon_node.rs:852] [ThreadId(14)] Received burnchain block #206 including block_commit_op (winning) - mtFzK54XtpktHj7fKonFExEPEGkUMsiXdy
INFO [1594131950.187] [testnet/stacks-node/src/neon_node.rs:872] [ThreadId(14)] Received burnchain block #206 including key_register_op - ST25WA53N4PWF8XZGQH2J5A4CGCWV4JADPM8MHTRV
INFO [1594131950.188] [testnet/stacks-node/src/neon_node.rs:651] [ThreadId(14)] Sleeping 0 before issuing tenure
INFO [1594131950.188] [testnet/stacks-node/src/neon_node.rs:412] [ThreadId(18)] Won sortition! stacks_header=4408acfcc516ae8ae86306811e82a45f3bf57a4a11ae0083a367af24d47ef645, burn_header=362906d75fa3a4e1a0c62af4802ffa2243f9f5aff0b445ef8ab6c5612d5b5fed
WARN [1594131950.342] [src/chainstate/stacks/db/transactions.rs:263] [ThreadId(18)] Bad nonce: origin account ST3WM51TCWMJYGZS1QFMC28DH5YP86782YGR113C1 nonce of tx 738e4d44636023efa08374033428e44eca490582bd39a6e61f3b6cf749b4214c is 0 (expected 1)
WARN [1594131950.342] [src/chainstate/stacks/miner.rs:144] [ThreadId(18)] Error processing TX 738e4d44636023efa08374033428e44eca490582bd39a6e61f3b6cf749b4214c: Bad nonce: origin account ST3WM51TCWMJYGZS1QFMC28DH5YP86782YGR113C1 nonce of tx 738e4d44636023efa08374033428e44eca490582bd39a6e61f3b6cf749b4214c is 0 (expected 1)
WARN [1594131950.345] [testnet/stacks-node/src/neon_node.rs:445] [ThreadId(18)] Failed to mine microblock: No transactions to mine
WARN [1594131950.391] [src/chainstate/stacks/miner.rs:652] [ThreadId(18)] Failed to apply tx 738e4d44636023efa08374033428e44eca490582bd39a6e61f3b6cf749b4214c: InvalidStacksTransaction("Invalid transaction anchor mode for anchored data")
INFO [1594131950.391] [src/chainstate/stacks/miner.rs:431] [ThreadId(18)] Miner: mined anchored block 3f9fdc4e92ebd54ac274e7f61b2eec17c38f78958cb85ccdd38ec2aa2d54598a, parent block 4408acfcc516ae8ae86306811e82a45f3bf57a4a11ae0083a367af24d47ef645
INFO [1594131950.395] [testnet/stacks-node/src/neon_node.rs:807] [ThreadId(18)] Stacks block assembled: 3f9fdc4e92ebd54ac274e7f61b2eec17c38f78958cb85ccdd38ec2aa2d54598a, with 1 txs
INFO [1594131950.435] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:378] [ThreadId(18)] Miner node: submitting leader_block_commit op - 04ee0b1602eb18fef7986887a7e8769a30c9df981d33c8380d255edef003abdcd243a0eb74afdf6740e6c423e62aec631519a24cf5b1d62bf8a3e06ddc695dcb77
INFO [1594131950.476] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:328] [ThreadId(18)] Miner node: submitting leader_key_register op - 04ee0b1602eb18fef7986887a7e8769a30c9df981d33c8380d255edef003abdcd243a0eb74afdf6740e6c423e62aec631519a24cf5b1d62bf8a3e06ddc695dcb77
test tests::neon_integrations::microblock_integration_test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 14 filtered out

   Doc-tests blockstack_lib
```

**Pull request merged**
