### PR TITLE
feat: add arm target to build script

### PR DESCRIPTION
**Pull request by zone117x**
Building off of @dantrevino's PR https://github.com/blockstack/stacks-blockchain/pull/1354
Add linux-armv7 binaries to the dist build script

### CODE REVIEW

**Comment by jcnelson** [comment]
This LGTM, but I have no way of verifying that the ARM binaries actually work.  Do you think we should say something in the README about how ARM has "second tier" status, whereas x86 has "first tier" status?  This is how other cross-arch projects handle setting expectations about different arch support.

**Comment by zone117x** [comment]
I agree with the tier status. Are we ready for publishing distributables to Github releases and/or other channels (e.g. homebrew https://github.com/blockstack/stacks-blockchain/issues/1369)?

Otherwise, these binaries have non-existent expectations outside of the Clarity-js-sdk repo (no distribution channels, no readme references, Circleci build artifacts have near zero visibility).

**Comment by jcnelson** [comment]
Hey @zone117x, the patch LGTM but please add the update to the README about tiered support so I can approve it.

I think we should make a separate issue about handling distributables and Github releases, since we'll want to address this for all other platforms as well.  I'm fine with making a distributable armv7 binary, as long as we can adequately communicate that it is unofficial (e.g. maybe we can put "unofficial" in the binary's filename).

**Comment by zone117x** [comment]
@jcnelson Sounds good -- we just don't currently release any binaries which is what I usually see with tier/support tables. I'm not quite sure what to state for tiers in the readme, e.g. "build scripts exist for tiers X, ...", "binaries are sometimes tested by PBC for tiers Y..."

**Comment by jcnelson** [comment]
> I'm not quite sure what to state for tiers in the readme, e.g. "build scripts exist for tiers X, ...", "binaries are sometimes tested by PBC for tiers Y..."

How about adding a section at the end about platform and arch support, and state that we provide official support for the Linux, Mac, and Windows builds on x64 but do not do so for the Linux aarch64 builds?

**Comment by zone117x** [comment]
Tier support note added to readme!

**Pull request merged**
