### PR TITLE
Forwarding receipts from boot procedure

### PR DESCRIPTION
**Pull request by lgalabru**

### CODE REVIEW

**Review by kantai — APPROVED** [review]
LGTM, thanks for the quick turnaround @lgalabru !

**Review by jcnelson — APPROVED** [review]
LGTM.  Thanks @lgalabru!

**Comment by jcnelson** [comment]
Just make sure the unit tests are passing before merging.

**Comment by diwakergupta** [comment]
@lgalabru this can be merged?

**Pull request merged**
