### PR TITLE
Remove redundant clones identified by Clippy.

### PR DESCRIPTION
**Pull request by diwakergupta**
Per
https://rust-lang.github.io/rust-clippy/rust-1.49.0/index.html#redundant_clone:

  Checks for a redundant clone() (and its relatives) which clones an
  owned value that is going to be dropped without further use.

  It is not always possible for the compiler to eliminate useless
  allocations and deallocations generated by redundant clone()s.

No functional changes.

### CODE REVIEW

**Review by lgalabru — APPROVED** [review]
Looks good to me!

**Review by kantai — COMMENTED** [review]
Given the number of changes in `next`, which should get merged to `master` before the next Xenon reset (soon), I think we should hold off on applying these changes just to avoid any merge conflicts.

**Comment by diwakergupta** [comment]
> Given the number of changes in `next`, which should get merged to `master` before the next Xenon reset (soon), I think we should hold off on applying these changes just to avoid any merge conflicts.

Yep, happy to hold off merging this. Not super critical anyways.

**Comment by diwakergupta** [comment]
Given the merge conflicts, easier to close this PR and open a new one.

**Pull request closed without merging**
